spring:
  profiles:
    active:
      - dog
      - EN
      - prod
banner:
  image:
    location: vizsla.jpg
guru:
  username: YmlUserName
  password: YmlPassword
  jdbcurl: YmUrl

---
spring:
  profiles: prod
guru:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcurl: YmProdUrl